name: $(BuildDefinitionName)-$(SourceBranchName)-$(BuildID)

resources:
  repositories:
  - repository: ci-settings
    type: github
    name: angr/ci-settings
    ref: refs/heads/default_pool
    endpoint: angr

stages:
- template: resources/master.yml@ci-settings
  parameters:
    container_image: angr/ci:async
